### ISSUE TITLE
Missing request-debug dependency

### ISSUE THREAD

**Issue by jamesjnadeau** [mcohen01/quickbooks#1]
Hi! first off, thanks for making this, I appreciate it.

I noticed that with debug enabled(admittedly haven't tried it without debug on), I get a missing package error:

`Error: Cannot find module 'request-debug'`

of course installing the package fixes the error, but hopefully you'll have a chance to fix this for the next guy.

If I had a dollar for every time I've made this mistake.....

Thanks again!

**Comment by mcohen01** [comment]
Thanks James!
