### ISSUE TITLE
bankAccount invalid

### ISSUE THREAD

**Issue by rbar2** [mcohen01/quickbooks#3]
Below is a modified version of the example from [this project's documentation](https://www.npmjs.com/package/quickbooks).  `charge` has been modified to use a `bankAccount` instead of a `card` (as [documented by Intuit as a payment method here](https://developer.intuit.com/docs/api/payments/echecks)), but it seems that the payment method is not currently supported by [the project](https://www.npmjs.com/package/quickbooks).

________________________________________________________________________________
**The resulting error is as follows:**

> { code: 'PMT-4000',
>        type: 'invalid_request',
>        message: 'bankAccount is invalid.',
>        detail: 'bankAccount',
>        infoLink: 'https://developer.intuit.com/v2/docs?redirectID=PayErrors' }

________________________________________________________________________________

**The modified example is as follows:**

```
var QuickBooks = require('quickbooks')
 
var qbo = new QuickBooks(consumerKey,
                         consumerSecret,
                         oauthToken,
                         oauthTokenSecret,
                         realmId,
                         false, // don't use the sandbox (i.e. for testing) 
                         true); // turn debugging on 
 
var chargeId
 
var charge = {
            amount :"42.21",
            bankAccount:{
                name:"John Smith",
                routingNumber:"123456789",  // note: I have tested this with valid routing & account numbers, though the same error is returned
                accountNumber:"987654321234",
                accountType:"PERSONAL_CHECKING",
                phone:"5555555555"
            },
            context:{
                deviceInfo:{
                  id:"1",
                  type:"type",
                  longitude:"longitude",
                  latitude:"",
                  phoneNumber:"5555555555",
                  macAddress:"macaddress",
                  ipAddress:"34"
                }
            },
            paymentMode:"WEB",
            checkNumber:"12345678",
            description:"Check Auth test call"
          };
 

qbo.charge(charge, function(err, charged) {
          console.log("err (below) = ");
          console.log(err);
          console.log("charged.id (below) = ");
          console.log(charged.id);
})
```

________________________________________________________________________________

Should the `charge` method of the [project](https://www.npmjs.com/package/quickbooks) currently be supporting Intuit's echeck payment method as well?

**Comment by mcohen01** [comment]
You probably want to use the [`echeck()`](https://developer.intuit.com/docs/api/payments/echecks) method rather than `charge()`

**Comment by rbar2** [comment]
You are absolutely correct.  Thank you very much.
